## CARGA LIBRERIAS 

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import joblib

## CARGA DE ARCHIVOS

In [2]:
df = pd.read_csv('s3://german-credit-80195/datos/original/german_credit_data.csv')

In [3]:
df["Risk"].value_counts()/df["Risk"].count()

good    0.7
bad     0.3
Name: Risk, dtype: float64

## SPLIT BASE DE DATOS 

In [4]:
train, test = train_test_split(df, test_size=0.3, 
                               random_state=42, stratify=df["Risk"])

In [5]:
train["Risk"].value_counts()/train["Risk"].count()

good    0.7
bad     0.3
Name: Risk, dtype: float64

In [6]:

test["Risk"].value_counts()/test["Risk"].count()



good    0.7
bad     0.3
Name: Risk, dtype: float64

### Dividir EN  train, test

In [8]:
train.to_csv('s3://german-credit-80195/datos/train/train.csv', index=False)
test.to_csv('s3://german-credit-80195/datos/test/test.csv', index=False)

## Exploracion 

In [9]:
pd.crosstab(index=train["Housing"], columns=train["Risk"], margins=True)

Risk     bad  good  All
Housing                
free      29    45   74
own      133   371  504
rent      48    74  122
All      210   490  700

In [10]:


tabla_sex = pd.crosstab(index=train["Sex"], columns=train["Risk"], margins=True)



tabla_sex



Risk    bad  good  All
Sex                   
female   76   138  214
male    134   352  486
All     210   490  700

In [11]:


tabla_sex["proba"] = tabla_sex.iloc[:, 1]/tabla_sex.iloc[:, 2]



tabla_sex



Risk    bad  good  All    proba
Sex                            
female   76   138  214  0.64486
male    134   352  486  0.72428
All     210   490  700  0.70000

## PREPROCESAMIENTO


##Imputación

In [12]:


from sklearn.impute import SimpleImputer



In [13]:

X_train = train[["Age", "Credit amount", "Duration"]]


In [14]:
imputer = SimpleImputer(strategy='mean')

In [15]:
imputer.fit(X_train)

SimpleImputer()

In [16]:
imputer.statistics_


array([  35.40285714, 3236.12142857,   21.04857143])

In [17]:
X_train["Age"].mean()

35.402857142857144

In [18]:

imputer.transform([[24, 1000, np.nan], 
                  [np.nan, np.nan, 12]])


array([[  24.        , 1000.        ,   21.04857143],
       [  35.40285714, 3236.12142857,   12.        ]])

In [19]:

imputer.fit_transform(X_train)


array([[3.100e+01, 4.473e+03, 3.600e+01],
       [4.600e+01, 1.829e+03, 1.500e+01],
       [2.700e+01, 7.418e+03, 6.000e+01],
       ...,
       [6.300e+01, 1.655e+03, 1.200e+01],
       [4.900e+01, 2.096e+03, 1.200e+01],
       [3.700e+01, 3.676e+03, 6.000e+00]])

In [20]:

from sklearn.impute import KNNImputer


In [21]:

imputer = KNNImputer(n_neighbors=2)


In [22]:

d = {'peso': [40, 42,44,45,39,80,82], 'edad': [19,20,21,23,25,27,30], 'nota':[3.0,3.1,None,4.1,5.0,None,4.8]}
dfs = pd.DataFrame(data=d)
dfs



peso  edad  nota
0    40    19   3.0
1    42    20   3.1
2    44    21   NaN
3    45    23   4.1
4    39    25   5.0
5    80    27   NaN
6    82    30   4.8

In [23]:


result = imputer.fit_transform(dfs)



In [24]:

result


array([[40.  , 19.  ,  3.  ],
       [42.  , 20.  ,  3.1 ],
       [44.  , 21.  ,  3.6 ],
       [45.  , 23.  ,  4.1 ],
       [39.  , 25.  ,  5.  ],
       [80.  , 27.  ,  4.45],
       [82.  , 30.  ,  4.8 ]])

## Escalado

In [25]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler

In [26]:
scaler = StandardScaler()


In [27]:


scaler.fit(X_train[["Age"]])



StandardScaler()

In [28]:

scaler.mean_


array([35.40285714])

In [29]:


scaler.var_ ** 0.5



array([11.23479253])

In [30]:
scaler.inverse_transform([[-0.39189483]])


array([[31.00000003]])

In [31]:


X_train["Age"]



328    31
891    46
255    27
243    27
492    27
       ..
73     41
401    28
769    63
2      49
617    37
Name: Age, Length: 700, dtype: int64

In [32]:
X_train["Age"].quantile(0.5)

33.0

In [33]:
X_train["Age"].quantile(0.5)

33.0

In [36]:
from sklearn.preprocessing import OneHotEncoder


In [37]:
encoder = OneHotEncoder(sparse=False, drop='first')
encoder.fit_transform(train[["Sex"]])


array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [38]:

encoder.categories_


[array(['female', 'male'], dtype=object)]

In [39]:

encoder.inverse_transform([[0]])


array([['female']], dtype=object)

## PIPELINE

### Pipeline de imputacion 

In [42]:
from sklearn.pipeline import Pipeline

In [43]:


numeric_pipeline = Pipeline(
    [
        ('Imputación con la media',   SimpleImputer(strategy='mean')),
        ('Escalado minmax', MinMaxScaler())
        
    ]
)



In [44]:


numeric_pipeline.fit(train[["Age", "Credit amount", "Duration"]])



Pipeline(steps=[('Imputación con la media', SimpleImputer()),
                ('Escalado minmax', MinMaxScaler())])

In [45]:


numeric_pipeline[0].statistics_



array([  35.40285714, 3236.12142857,   21.04857143])

In [46]:


numeric_pipeline[1].min_



array([-0.36363636, -0.01375592, -0.05882353])

In [47]:


numeric_pipeline[1].data_max_



array([   75., 18424.,    72.])

In [48]:
train[["Age", "Credit amount", "Duration"]].max()

Age                 75
Credit amount    18424
Duration            72
dtype: int64

In [49]:


numeric_pipeline.transform(train[["Age", "Credit amount", "Duration"]])



array([[0.2       , 0.23236492, 0.47058824],
       [0.47272727, 0.08688236, 0.16176471],
       [0.12727273, 0.3944096 , 0.82352941],
       ...,
       [0.78181818, 0.07730824, 0.11764706],
       [0.52727273, 0.10157368, 0.11764706],
       [0.30909091, 0.18851106, 0.02941176]])

In [50]:

numeric_pipeline.transform([[np.nan, np.nan, np.nan]])


array([[0.28005195, 0.16430733, 0.25071429]])

### Pipeline Categrorico

In [53]:


categorical_pipeline = Pipeline(
        [
            ('imputación moda', SimpleImputer(strategy='most_frequent')),
            ('onehot encoder', OneHotEncoder(sparse=False))
        ]

)



In [54]:


categorical_pipeline.fit(train[["Sex", "Purpose", "Housing"]])



Pipeline(steps=[('imputación moda', SimpleImputer(strategy='most_frequent')),
                ('onehot encoder', OneHotEncoder(sparse=False))])

In [55]:
categorical_pipeline.transform(train[["Sex", "Purpose", "Housing"]])

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

### Pipeline transformacion de Columna 

In [56]:

from sklearn.compose import ColumnTransformer


In [57]:


column_transformer = ColumnTransformer(
            [
                ('numeric pipeline', numeric_pipeline, [0, 1, 2]),
                ('categorical pipeline', categorical_pipeline, [3, 4, 5])
            ]
)



In [58]:


column_transformer.fit(train[["Age", 
                             "Credit amount",
                              "Duration",
                              "Sex",
                              "Purpose",
                              "Housing"]])



ColumnTransformer(transformers=[('numeric pipeline',
                                 Pipeline(steps=[('Imputación con la media',
                                                  SimpleImputer()),
                                                 ('Escalado minmax',
                                                  MinMaxScaler())]),
                                 [0, 1, 2]),
                                ('categorical pipeline',
                                 Pipeline(steps=[('imputación moda',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot encoder',
                                                  OneHotEncoder(sparse=False))]),
                                 [3, 4, 5])])

In [60]:


column_transformer.transform(train[["Age", 
                             "Credit amount",
                              "Duration",
                              "Sex",
                              "Purpose",
                              "Housing"]])



array([[0.2       , 0.23236492, 0.47058824, ..., 0.        , 1.        ,
        0.        ],
       [0.47272727, 0.08688236, 0.16176471, ..., 0.        , 1.        ,
        0.        ],
       [0.12727273, 0.3944096 , 0.82352941, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.78181818, 0.07730824, 0.11764706, ..., 0.        , 1.        ,
        0.        ],
       [0.52727273, 0.10157368, 0.11764706, ..., 0.        , 1.        ,
        0.        ],
       [0.30909091, 0.18851106, 0.02941176, ..., 0.        , 0.        ,
        1.        ]])

## TRANSFORMA A joblib

In [61]:


joblib.dump(column_transformer, 'preprocessing.joblib')



['preprocessing.joblib']